name: flutter_unity_widget_example
description: Demonstrates how to use the flutter_unity_widget plugin.


publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_unity_widget:
    path: ../
  pointer_interceptor: ^0.9.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
